#######################################################
# 
# Circle.py
# Python implementation of the Class Circle
# Generated by Enterprise Architect
# Created on:      15-Mar-2021 12:48:50 AM
# Original author: User
# 
#######################################################
from PyQt5.QtGui import QPen, QBrush

from shapes.Ellipse import Ellipse

class Circle(Ellipse):
    @staticmethod
    def name():
        return 'Circle'
    # def __init__(self,points,brd_color,bg_color):
    #     super(Circle, self).__init__(points,brd_color,bg_color)
