#######################################################
# 
# shape.py
# Python implementation of the Class shape
# Generated by Enterprise Architect
# Created on:      15-Mar-2021 12:48:51 AM
# Original author: User
# 
#######################################################
from PyQt5.QtGui import QPen

from utils import Point


class Shape:
    def __init__(self,points,brd_color='black',bg_color='white'):
        self.bg_color = bg_color
        self.brd_color = brd_color
        self.points = points
    def draw(self):
        pass
    def get_pen(self):
        return QPen(self.brd_color,3)
    def get_bg_color(self):
        return self.bg_color

    def get_brd_color(self):
        return self.brd_color

    def get_points(self):
        return self.points

    def get_location(self):
        return self.location

    def move(self,dest):
        dx, dy = dest.x()-self.location.x(), dest.y() - self.location.y()
        self.location = dest
        for i in range(len(self.points)):
            self.points[i] = Point(self.points[i].x() + dx, self.points[i].y() + dy)
    def set_bg_color(self,color):
        self.bg_color = color

    def set_brd_color(self,color):
        self.brd_color = color

    def set_points(self,points):
        self.points = points