#######################################################
# 
# Rectangle.py
# Python implementation of the Class Rectangle
# Generated by Enterprise Architect
# Created on:      15-Mar-2021 12:48:51 AM
# Original author: User
# 
#######################################################

from PyQt5.QtGui import QBrush, QPen

from utils import distance, mbr, Point
from shapes.Shape import Shape


class Rectangle(Shape):
    @staticmethod
    def name():
        return 'Rectangle'

    def __init__(self, points, brd_color, bg_color):
        if len(points) > 2:
            points = [Point(*p) for p in mbr(points)]
            self._width = (points[1].x() - points[0].x()) / 2
            self._height = (points[1].y() - points[0].y()) / 2
            self.location = Point(points[0].x() + self._width,
                                  points[0].y() + self._height)
        else:
            self._width = distance(points[0], points[1])
            self._height = self._width
            self.location = points[0]
        super(Rectangle, self).__init__(points, brd_color, bg_color)

    def draw(self, painter):
        painter.setPen(self.get_pen())
        painter.setBrush(QBrush(self.bg_color))
        painter.drawRect(self.location.x() - self._width, self.location.y() - self._height, 2 * self._width,
                         2 * self._height)
