#######################################################
# 
# Square.py
# Python implementation of the Class Square
# Generated by Enterprise Architect
# Created on:      15-Mar-2021 12:48:52 AM
# Original author: User
# 
#######################################################
from PyQt5.QtGui import QPen, QBrush

from shapes.Rectangle import Rectangle


class Square(Rectangle):
    @staticmethod
    def name():
        return 'Square'
